# Generated by Django 3.2 on 2021-05-31 20:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storemaster', '0009_alter_webstore_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.PositiveIntegerField(choices=[(1, 'pending'), (2, 'out for delivery'), (3, 'delivered')], default=1)),
                ('webstore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storemaster.webstore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
