# Generated by Django 3.2 on 2021-05-31 20:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'In stock'), (0, 'Out of stock')], default=1)),
                ('product_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='')),
                ('product_video', models.FileField(blank=True, null=True, upload_to='')),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('shipping_charge', models.IntegerField(blank=True, null=True)),
                ('net_amount', models.IntegerField(blank=True, null=True)),
                ('offer_percentage', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
