# Generated by Django 3.2 on 2021-06-09 14:28

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210609_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[800, 800], upload_to='products'),
        ),
    ]
