# Generated by Django 3.2 on 2021-05-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210524_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcode',
            old_name='post_code',
            new_name='pin_code',
        ),
    ]
