# Generated by Django 3.2 on 2021-05-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_post_code_postcode_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'customer'), (1, 'store owner'), (2, 'employee')], default=3),
        ),
    ]
