# Generated by Django 3.2 on 2021-05-23 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_post_code_postcode_pin_code'),
        ('storemaster', '0002_remove_webstore_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstore',
            name='post_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.postcode'),
        ),
    ]
