# Generated by Django 3.2 on 2021-05-23 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storemaster', '0004_auto_20210524_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webstore',
            name='id',
        ),
        migrations.AlterField(
            model_name='webstore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
