# Generated by Django 3.2 on 2021-05-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storemaster', '0005_auto_20210524_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webstore',
            old_name='store_name',
            new_name='name',
        ),
    ]
