# Generated by Django 3.2 on 2021-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemaster', '0008_auto_20210526_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstore',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
